name: AndroidBuild

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main

concurrency:
  group: build-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Release App
    runs-on: ubuntu-latest
    environment: my-release-key.b64

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        if: github.repository == 'dilip2882/QRVentory' && github.event_name == 'push'
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload APK
        if: "!startsWith(github.ref, 'refs/tags/') && github.repository == 'dilip2882/QRVentory' && github.event_name == 'push'"
        uses: actions/upload-artifact@v4
        with:
          name: QRVentory.apk
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

      # Create new release
      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'dilip2882/QRVentory'
        id: get_tag_name
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Rename artifact
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'ivaniskandar/shouko'
        run: cp app/build/outputs/apk/release/app-release-unsigned.apk QRVentory-${{ env.VERSION_TAG }}.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'dilip2882/QRVentory'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: ${{ env.VERSION_TAG }}
          files: QRVentory-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
