name: Release Builder

on:
  push:
    branches:
      - 'release'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Release App
    runs-on: ubuntu-latest
    environment: my-release-key.b64

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      # Set up Android SDK using the dedicated action
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      # Make `gradlew` executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build App and Run Unit Tests
        run: ./gradlew spotlessCheck assembleStandardRelease testStandardReleaseUnitTest --stacktrace
        continue-on-error: true  # Ignore errors

      - name: Debug Secrets
        run: |
          echo "Checking secrets"
          echo "SIGNING_KEY exists: ${{ secrets.SIGNING_KEY != '' }}"
          echo "KEY_STORE_PASSWORD exists: ${{ secrets.KEY_STORE_PASSWORD != '' }}"
          echo "KEY_PASSWORD exists: ${{ secrets.KEY_PASSWORD != '' }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload Mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

      - name: List APK Directory
        run: ls app/build/outputs/apk/release/

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean Up Build Artifacts
        run: |
          set -e
          declare -A APKS=(
            ["QRVentory.apk"]="app-standard-universal-release-unsigned-signed.apk"
            ["QRVentory-arm64-v8a.apk"]="app-standard-arm64-v8a-release-unsigned-signed.apk"
            ["QRVentory-armeabi-v7a.apk"]="app-standard-armeabi-v7a-release-unsigned-signed.apk"
            ["QRVentory-x86.apk"]="app-standard-x86-release-unsigned-signed.apk"
            ["QRVentory-x86_64.apk"]="app-standard-x86_64-release-unsigned-signed.apk"
          )
          for apk in "${!APKS[@]}"; do
            cp app/build/outputs/apk/release/${APKS[$apk]} $apk
            sha=$(sha256sum $apk | awk '{ print $1 }')
            echo "${apk^^}_SHA=$sha" >> $GITHUB_ENV
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: QRVentory
          body: |
            ---
            ### Checksums

            | Variant        | SHA-256                  |
            |----------------|--------------------------|
            | Universal      | ${{ env.QRVENTORY_APK_SHA }} |
            | arm64-v8a     | ${{ env.QRVENTORY_ARM64_V8A_SHA }} |
            | armeabi-v7a   | ${{ env.QRVENTORY_ARMEABI_V7A_SHA }} |
            | x86           | ${{ env.QRVENTORY_X86_SHA }} |
            | x86_64        | ${{ env.QRVENTORY_X86_64_SHA }} |

            ## If you are unsure which version to choose, go with QRVentory.apk
          files: |
            QRVentory.apk
            QRVentory-arm64-v8a.apk
            QRVentory-armeabi-v7a.apk
            QRVentory-x86.apk
            QRVentory-x86_64.apk
          draft: true
          prerelease: yes
        env:
          GITHUB_TOKEN: ${{ secrets.QRVENTORY_GITHUB_TOKEN }}
