name: Release Builder

on:
  push:
    branches:
      - 'release'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Release App
    runs-on: ubuntu-latest
    environment: my-release-key.b64

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Android SDK
        run: |
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build App and Run Unit Tests
        run: ./gradlew spotlessCheck assembleStandardRelease testStandardReleaseUnitTest --stacktrace
        continue-on-error: true  # Ignore errors

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QRVentory.apk
          path: app/build/outputs/apk/release/app-release.apk
