name: Release Builder

on:
  push:
    branches:
      - 'release'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Release App
    runs-on: ubuntu-latest
    environment: my-release-key.b64

    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      # Set up Android SDK using the dedicated action
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build App and Run Unit Tests
        run: ./gradlew spotlessCheck assembleStandardRelease testStandardReleaseUnitTest --stacktrace

      - name: Debug Secrets
        run: |
          echo "Checking secrets"
          echo "SIGNING_KEY exists: ${{ secrets.SIGNING_KEY != '' }}"
          echo "KEY_STORE_PASSWORD exists: ${{ secrets.KEY_STORE_PASSWORD != '' }}"
          echo "KEY_PASSWORD exists: ${{ secrets.KEY_PASSWORD != '' }}"

      - name: Sign APK
